[package]
name = "boc-rs"
version = "0.1.0"
authors = ["LiJia <lijia@aifantai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = "3.0.0-beta.2"
chrono="0.4"
